version: '3.8'

networks:
  default:

services:
  db:
    image: mysql:8.0
    container_name: conference
    ports:
    - 3306
    volumes:
    - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: rcg27
      MYSQL_DATABASE: conference